[theme]
base="light"
primaryColor="#b40b08"
font="Atkinson Hyperlegible Next"

[[theme.fontFaces]]
family="Atkinson Hyperlegible Next"
url="app/static/fonts/AtkinsonHyperlegibleNext-Regular.woff2"
style="normal"

[[theme.fontFaces]]
family="Atkinson Hyperlegible Next"
url="app/static/fonts/AtkinsonHyperlegibleNext-RegularItalic.woff2"
style="italic"

[server]
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true
